// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-D_IsR0ySnoiSP3XcEmsavVq_lZuR_w',
    appId: '1:1009548471879:web:21acf400fcb34d86d98b62',
    messagingSenderId: '1009548471879',
    projectId: 'ecobuddy-153ba',
    authDomain: 'ecobuddy-153ba.firebaseapp.com',
    storageBucket: 'ecobuddy-153ba.firebasestorage.app',
    measurementId: 'G-JZ9D540PQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHqKZaTxLxLF_Y_6Hl1zvTIw0p4i_vos',
    appId: '1:1009548471879:android:0bb39e235d03c609d98b62',
    messagingSenderId: '1009548471879',
    projectId: 'ecobuddy-153ba',
    storageBucket: 'ecobuddy-153ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cLwGnV_oCLefWStrVjpnra1xL0_CFOw',
    appId: '1:1009548471879:ios:7fe2bf48de7a5684d98b62',
    messagingSenderId: '1009548471879',
    projectId: 'ecobuddy-153ba',
    storageBucket: 'ecobuddy-153ba.firebasestorage.app',
    androidClientId: '1009548471879-qggiljg466ah42u2c2otvtmu9ovkun94.apps.googleusercontent.com',
    iosClientId: '1009548471879-170859ckeqsnu86n4rpni623iimh9ied.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cLwGnV_oCLefWStrVjpnra1xL0_CFOw',
    appId: '1:1009548471879:ios:7fe2bf48de7a5684d98b62',
    messagingSenderId: '1009548471879',
    projectId: 'ecobuddy-153ba',
    storageBucket: 'ecobuddy-153ba.firebasestorage.app',
    iosBundleId: 'com.example.ecoDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ-D_IsR0ySnoiSP3XcEmsavVq_lZuR_w',
    appId: '1:1009548471879:web:ab8b03eba0f8bddbd98b62',
    messagingSenderId: '1009548471879',
    projectId: 'ecobuddy-153ba',
    authDomain: 'ecobuddy-153ba.firebaseapp.com',
    storageBucket: 'ecobuddy-153ba.firebasestorage.app',
    measurementId: 'G-W63NM4NNF2',
  );

}